const documents = {
    'id':1,
    'versions':{
        1:{
        'component_hierachy':[
            {
                'id':1,
                'parent':null,
                'children':[2,3],
                'siblings':[]
            },
            {
                'id':2,
                'parent':1,
                'children':[],
                'siblings':[]
            },
            {
                'id':3,
                'parent':1,
                'children':[],
                'siblings':[]
            }
        ]
        },
        2:{
            'component_hierachy':[
                {
                    'id':1,
                    'parent':null,
                    'children':[2,3],
                    'siblings':[]
                },
                {
                    'id':2,
                    'parent':1,
                    'children':[],
                    'siblings':[]
                },
                {
                    'id':3,
                    'parent':1,
                    'children':[],
                    'siblings':[]
                }
            ]
        }
    }    
}
export { components}